pipeline:
  name: my-pipeline-stage-barriers
  identifier: mypipelinestagebarriers
  projectIdentifier: studentab4d461d5d
  orgIdentifier: InstructorLedTraining
  tags: {}
  stages:
    - parallel:
        - stage:
            name: ums-backend
            identifier: umsbackend
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: my_service
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      manifests:
                        - manifest:
                            identifier: mymanifest
                            type: K8sManifest
                            spec:
                              store:
                                type: Git
                                spec:
                                  paths: <+input>
                                  repoName: <+input>
                              valuesPaths: <+input>
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              environment:
                environmentRef: my_dev_env
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: my_dev_k8s
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                  - step:
                      type: Barrier
                      name: my-breakpoint
                      identifier: mybreakpoint
                      spec:
                        barrierRef: mystagebarrier
                      timeout: 10m
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: my-parallel-validation
            identifier: myparallelvalidation
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: Barrier
                      name: my-validation-breakpoint
                      identifier: myvalidationbreakpoint
                      spec:
                        barrierRef: mystagebarrier
                      timeout: 10m
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: |-
                              #curl -O -v http://ums.my-dev-env-ns.svc.cluster.local:8080/api/v1/configinfo | true
                              curl https://jsonplaceholder.typicode.com/todos/1
                        environmentVariables: []
                        outputVariables: []
                        delegateSelectors:
                          - my-delegate
                      timeout: 10m
            tags: {}
  flowControl:
    barriers:
      - name: my-stage-barrier
        identifier: mystagebarrier
  variables:
    - name: replicacount
      type: String
      description: ""
      required: false
      value: "1"
