pipeline:
  name: my-serviceoverride-pipeline
  identifier: myserviceoverridepipeline
  projectIdentifier: studentab4d461d5d
  orgIdentifier: InstructorLedTraining
  tags: {}
  stages:
    - stage:
        name: my-serviceoverride
        identifier: myserviceoverride
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: mynginxservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: my_dev_env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dummyns
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: replicacount
      type: String
      description: ""
      required: false
      value: "1"
